### PR TITLE
AV-1530 As a product owner I want new static error page implemented

### PR DESCRIPTION
**Pull request by bertofl90**

### CODE REVIEW

**Review by Zharktas — CHANGES_REQUESTED** [review]
Why the styles are implemented as inline compared to the previous styles.css file ? Now when styles are updated, the developer needs to modify three files instead on one.

Additionally the font is wrong one in the new styles, they are rendered as Times New Roman instead of Source Sans

**Comment by bertofl90** [comment]
> 

I've move the styles and update the fonts

**Review by Zharktas — CHANGES_REQUESTED** [review]
The font needs to be added separately as it is a webfont and not one of those coming with OS.

**Comment by Zharktas** [comment]
Implemented in https://github.com/vrk-kpa/opendata-ckan/pull/32

**Pull request closed without merging**
