### PR TITLE
AV-1809: Fixed broken links report

### PR DESCRIPTION
**Pull request by teravill**
Fixed broken links report page

### CODE REVIEW

**Review by Zharktas — CHANGES_REQUESTED** [review]
https://github.com/vrk-kpa/ckanext-report/compare/52dd947ebce1b38bd42512315c29d6fb5cd2cb03...b434e8351eb844a78389cacc35f354a09d66a347#diff-5c6c02d2d6b2ea8efe6cd33bb1435bf19b8c565775572b7a69ebba2661f4d410R12-R15

This should not refer to broken links report, as it affects other reports as well.

https://github.com/vrk-kpa/ckanext-report/compare/52dd947ebce1b38bd42512315c29d6fb5cd2cb03...b434e8351eb844a78389cacc35f354a09d66a347#diff-e39bbbae8afdbb6d2a257da6521aebe193f7a283ea2e7c85640de292f99a0e55R45-R56

Generating specific urls should use `url_for` helper as urls generated manually usually have side effects. https://github.com/vrk-kpa/ckanext-report/compare/52dd947ebce1b38bd42512315c29d6fb5cd2cb03...b434e8351eb844a78389cacc35f354a09d66a347#diff-203d3a2605b7444ad4a1db665222ea3df649d43fe218acf3d5c87e432f2636b4R55 same in here, not all instances are hosted in `/data/` path

**Comment by teravill** [comment]
> [vrk-kpa/ckanext-report@52dd947...b434e83#diff-5c6c02d2d6b2ea8efe6cd33bb1435bf19b8c565775572b7a69ebba2661f4d410R12-R15](https://github.com/vrk-kpa/ckanext-report/compare/52dd947ebce1b38bd42512315c29d6fb5cd2cb03...b434e8351eb844a78389cacc35f354a09d66a347#diff-5c6c02d2d6b2ea8efe6cd33bb1435bf19b8c565775572b7a69ebba2661f4d410R12-R15)
> 
> This should not refer to broken links report, as it affects other reports as well.
> 
> [vrk-kpa/ckanext-report@52dd947...b434e83#diff-e39bbbae8afdbb6d2a257da6521aebe193f7a283ea2e7c85640de292f99a0e55R45-R56](https://github.com/vrk-kpa/ckanext-report/compare/52dd947ebce1b38bd42512315c29d6fb5cd2cb03...b434e8351eb844a78389cacc35f354a09d66a347#diff-e39bbbae8afdbb6d2a257da6521aebe193f7a283ea2e7c85640de292f99a0e55R45-R56)
> 
> Generating specific urls should use `url_for` helper as urls generated manually usually have side effects. [vrk-kpa/ckanext-report@52dd947...b434e83#diff-203d3a2605b7444ad4a1db665222ea3df649d43fe218acf3d5c87e432f2636b4R55](https://github.com/vrk-kpa/ckanext-report/compare/52dd947ebce1b38bd42512315c29d6fb5cd2cb03...b434e8351eb844a78389cacc35f354a09d66a347#diff-203d3a2605b7444ad4a1db665222ea3df649d43fe218acf3d5c87e432f2636b4R55) same in here, not all instances are hosted in `/data/` path

Fixed in [cf56bb2](https://github.com/vrk-kpa/opendata/pull/1686/commits/cf56bb2f5bbcfaebb2b5f345ee2aabb73cd48047)

**Review by teravill — COMMENTED** [review]
Fixed in [cf56bb2](https://github.com/vrk-kpa/opendata/pull/1686/commits/cf56bb2f5bbcfaebb2b5f345ee2aabb73cd48047)

**Review by beazil — CHANGES_REQUESTED** [review]
When used on templates, these functions should be added in `plugin/__init__.py` -> `get_helpers`, now it gives an error about undefined helper function for me

https://github.com/vrk-kpa/ckanext-report/compare/52dd947ebce1b38bd42512315c29d6fb5cd2cb03...c70efd0a0e963439283ba3de901c8ba0ab3a1879#diff-e39bbbae8afdbb6d2a257da6521aebe193f7a283ea2e7c85640de292f99a0e55R45-R60

**Review by teravill — COMMENTED** [review]
Fixed in [8a080ca](https://github.com/vrk-kpa/opendata/pull/1686/commits/8a080ca96543fa60e969775f5043f1d30aa87e91)

**Review by beazil — APPROVED** [review]

**Review by Zharktas — APPROVED** [review]
broken_links.html might require some updates to url generation but those elements might not be actually in use, so I'll approve this anyway.

**Pull request merged**
